## Day Objectives
- Data Structures in python
    - List
        - Mutable
        - Ordered and allow duplicates
        - we can store heterogeneous data
        - indexing starts from 0
        - slicing 
            - list_name[start:stop:step]
        - Built-in methods: dir(list)
    - Tuple
        - Ordered and Immutable
        - Indexing and slicing are same like lists
        - allow duplicates
        - Built-in methods: dir(tuple)
    - Set
        - Unordered and Mutable
        - Doesn't allow duplicates
        - indexing not possible
        - Built-in methods: dir(set)
    - Dictionaries
        - we can store the data as key:value pairs
        - keys are immutable and unique
        - values may duplicate.
        - Built-in methods: dir(dict)
- Data Analytics
    - numpy

In [1]:
li = [8,60,5,27,'aditya',9.8,'AEC']
print(li)

[8, 60, 5, 27, 'aditya', 9.8, 'AEC']


In [4]:
# 'aditya'
print(li[4])
print(li[-3])

aditya
aditya


In [5]:
li

[8, 60, 5, 27, 'aditya', 9.8, 'AEC']

In [6]:
# 8 60 5 27
li[0:4]

[8, 60, 5, 27]

In [8]:
# how can we print all alternative elements in a given list
# 8 5 'aditya' 'AEC'
li[0::2]
li[::2]

[8, 5, 'aditya', 'AEC']

In [9]:
li[::-2]

['AEC', 'aditya', 5, 8]

In [10]:
li[::-1]

['AEC', 9.8, 'aditya', 27, 5, 60, 8]

In [12]:
li

[8, 60, 5, 27, 'aditya', 9.8, 'AEC']

In [15]:
# aytida
li[-3][::-1]
li[4][::-1]

'aytida'

In [16]:
li = [1,2,3,1,2,4,4,5,7,8]
a = []
for i in li:
    if i not in a:
        a.append(i)
print(a)

[1, 2, 3, 4, 5, 7, 8]


In [17]:
unique=[]
for i in li:
    if li.count(i) is 1: # li.count(i)==1
        unique.append(i)
print(unique)

[3, 5, 7, 8]


In [18]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [19]:
dir(tuple)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [20]:
li

[1, 2, 3, 1, 2, 4, 4, 5, 7, 8]

In [22]:
s = {1, 2, 3, 1, 2, 4, 4, 5, 7, 8}
t = (1, 2, 3, 1, 2, 4, 4, 5, 7, 8)
l = [1, 2, 3, 1, 2, 4, 4, 5, 7, 8]
print(len(s),len(t),len(l))

7 10 10


In [23]:
print(s)
print(t)
print(l)

{1, 2, 3, 4, 5, 7, 8}
(1, 2, 3, 1, 2, 4, 4, 5, 7, 8)
[1, 2, 3, 1, 2, 4, 4, 5, 7, 8]


In [24]:
# un-ordered
s = {39,1,45,37,100,98,24}
print(s)

{1, 98, 100, 37, 39, 45, 24}


In [25]:
s[2]

TypeError: 'set' object is not subscriptable

- set operations
    - Union(|)  --> Combination of both set elements
    - Intersection(&)  --> Common elements in both sets
    - Difference(-)  --> remaining elements in first set after removing common elements
    - Symmetric Difference(^)  --> Combination of both set elements except common elements

In [26]:
dir(set)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [30]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}

print(a.difference(b))
print(a.intersection(b))
print(b.union(a))
print(b.symmetric_difference(a))

{1, 2, 3}
{4, 5}
{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 6, 7, 8}


In [31]:
print(a)
print(b)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8}


In [32]:
a.difference_update(b)
print(a)
print(b)

{1, 2, 3}
{4, 5, 6, 7, 8}


In [33]:
b.symmetric_difference_update(a)
print(a)
print(b)

{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8}


In [34]:
b.intersection_update(a)
print(a)
print(b)

{1, 2, 3}
{1, 2, 3}


In [36]:
a.difference_update(b)
print(a)
print(b)

set()
{1, 2, 3}


In [40]:
s.remove(24)

KeyError: 24

In [48]:
s.discard(45)

In [49]:
s

{1, 37, 39, 98, 100}

In [51]:
dir(dict)

['__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [52]:
d = {100:'apple',20:'guava',50:'mango'}
d.fromkeys(['banana','grapes'],60)

{'banana': 60, 'grapes': 60}

In [53]:
d

{100: 'apple', 20: 'guava', 50: 'mango'}

In [54]:
d.update({130:'pineapple'})
print(d)

{100: 'apple', 20: 'guava', 50: 'mango', 130: 'pineapple'}


- WAP to create a dictionary where key is character in ur name and value is ascii value of that character

```
i/p: enter ur name: abcd
o/p: {'a':97,'b':98,'c':99,'d':100}
```

- WAP to create a dictionary like
```
i/p: aabbbcds
o/p: {'a':2,'b':3,'c':1,'d':1,'s':1}
```

In [55]:
# Task-1
s = input("Enter ur name: ")
d = {}
for i in s:
    d[i]=ord(i)
print(d)

Enter ur name: divya
{'d': 100, 'i': 105, 'v': 118, 'y': 121, 'a': 97}


In [56]:
# Task-2
s = input("Enter a string: ")
char_freq = {}
for i in s:
    if i in char_freq:
        char_freq[i] += 1
    else:
        char_freq[i] = 1
print(char_freq)

Enter a string: malayalam
{'m': 2, 'a': 4, 'l': 2, 'y': 1}


### Data Analysis:
- Numpy(Numerical Python)
    - Numpy is a open source in python package
    - Numpy array stores only homogenous data
    - Used for scientific calculations
    - Numpy is used to create multi dimensional arrays for fast operations.
    - numpy is mainly working with arrays.
    - If you want to install numpy in other idle's
        - pip install numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
li=[2,3,4,5]
print(li)
type(li)

[2, 3, 4, 5]


list

In [20]:
a=np.array([2,3,4,5])  #1-d array
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(np.append(a,[8,9]))
print(a.nbytes)

[2 3 4 5]
<class 'numpy.ndarray'>
1
(4,)
int32
[2 3 4 5 8 9]
16


In [26]:
# 2-D array
b=np.array([[2,3,4,5],[8,7,9,10]]) 
print(b)
print(b.ndim)
print(b.itemsize)
print(type(b))
print(b.shape)

[[ 2  3  4  5]
 [ 8  7  9 10]]
2
4
<class 'numpy.ndarray'>
(2, 4)


In [35]:
# 3-D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [38]:
a

array([2, 3, 4, 5])

In [40]:
a[1::3]

array([3])

In [41]:
b

array([[ 2,  3,  4,  5],
       [ 8,  7,  9, 10]])

In [44]:
b[0,2]

4

In [45]:
b[:,3]

array([ 5, 10])

In [46]:
#7 9
b[1,1:3]

array([7, 9])

In [47]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
c[1,0,1]

6

In [49]:
c[:,1,1]

array([4, 8])

In [50]:
c[:,:,0]

array([[1, 3],
       [5, 7]])

In [51]:
l = np.array(range(10))
print(l)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
# arange()
m = np.arange(10)
print(m)
print(type(m))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [57]:
n = np.arange(10,40,2)
print(n)

[10 12 14 16 18 20 22 24 26 28]


In [63]:
n = np.arange(1,10).reshape(9,1)
print(n)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [65]:
m = np.arange(20,40,2).reshape(5,2)
m

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [67]:
l = np.arange(12).reshape(3,2,2,1)
l

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]]])

In [68]:
l[:,1,0,0]

array([ 2,  6, 10])

In [69]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [76]:
# linspace()
p = np.linspace(1,10,10)


array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [77]:
#logspace()
r = np.logspace(1,10,30)
r

array([1.00000000e+01, 2.04335972e+01, 4.17531894e+01, 8.53167852e+01,
       1.74332882e+02, 3.56224789e+02, 7.27895384e+02, 1.48735211e+03,
       3.03919538e+03, 6.21016942e+03, 1.26896100e+04, 2.59294380e+04,
       5.29831691e+04, 1.08263673e+05, 2.21221629e+05, 4.52035366e+05,
       9.23670857e+05, 1.88739182e+06, 3.85662042e+06, 7.88046282e+06,
       1.61026203e+07, 3.29034456e+07, 6.72335754e+07, 1.37382380e+08,
       2.80721620e+08, 5.73615251e+08, 1.17210230e+09, 2.39502662e+09,
       4.89390092e+09, 1.00000000e+10])

In [82]:
# zeros()
z = np.zeros((4,5),dtype=int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [84]:
#ones
o=np.ones((5,4,2,3))
o

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [87]:
#full
f=np.full((3,4),12)
f

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [88]:
np.diag(f)

array([12, 12, 12])

In [89]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [92]:
np.max(c,axis=1)

array([[3, 4],
       [7, 8]])

In [95]:
np.min(c)

1

In [96]:
np.mean(c)

4.5

In [98]:
np.median(c)

4.5

In [ ]:
li = [3,4,1,2,6,7]
cs = [3,7,8,10,16,23]
cp = [3,12,12,24,144,1008]